name: Build and Test Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Run type checking
        run: npm run typecheck
      
      - name: Run tests
        run: npm test
      
      - name: Build action
        run: npm run build
      
      - name: Verify action files
        run: |
          if [ ! -f "dist/action/main.js" ]; then
            echo "Error: dist/action/main.js not found after build"
            exit 1
          fi
          echo "✅ Action build successful"

  validate-action:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build action
        run: npm run build
      
      - name: Test action loading (dry run)
        uses: ./
        with:
          safe-address: '0x0000000000000000000000000000000000000000'
          safe-network: 'sepolia'
          rpc-url: 'https://sepolia.infura.io/v3/dummy'
          proposer-private-key: '0x0000000000000000000000000000000000000000000000000000000000000001'
          foundry-script-path: 'script/dummy.s.sol'
          action-mode: 'list-pending'
          dry-run: true
        continue-on-error: true
        
      - name: Validate action metadata
        run: |
          if [ ! -f "action.yml" ]; then
            echo "Error: action.yml not found"
            exit 1
          fi
          echo "✅ Action metadata validated"
